### ISSUE TITLE
Mod is broken

### ISSUE THREAD

**Issue by korAPUcard** [linuxgurugamer/REKT#9] opened 2024-03-31 07:11 UTC
All pods and parts causes game crash when launched spacecraft on any launch sites(Launchpad, Airport, etc.).

Details:

- Game mod is latest version.
- All installed mods version is latest version.
- I'm already tried game verify check.
- All dependency mods already installed.

PC Spec:

- OS: Windows 11 Pro x64
- CPU: Intel Core i7 12650H
- RAM: DDR5 32GB(16x2) Dual Channel
- GPU: NVIDIA GeForce RTX 4060 Laptop GPU
- Storage: SSD 2TB x1, HDD 2TB x1

I think this is not a PC problem. Because other mods is not causing any problem. Only this mod is broken. Please update your mod.

**Comment by linuxgurugamer** [comment] 2024-03-31 11:16
With all those details, I still know nothing.

Please repost this, along with the Player.log file, on the KSP Forum, here:
https://forum.kerbalspaceprogram.com/index.php?/topic/181613-145-151-161-rekt-escape-pod-mod/

And a full description of what you were doing when the crash happened

And before you post and ask where that file is, read the following post which tells you where the file is:
https://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/
Read this BEFORE asking for support: [http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/](https://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/)

**Comment by linuxgurugamer** [comment] 2024-03-31 11:42
I did some testing on this for you, I'm pretty sure the issue is with the RasterPropMonitor mod, which this uses if available.
I suggest doing what I said above, and contact the maintainer there:  
https://forum.kerbalspaceprogram.com/index.php?/topic/190737-18x-110x-rasterpropmonitor-adopted/

**Comment by JonnyOThan** [comment] 2024-03-31 12:26
This should be fixed in REKT.  You need to add the RPM computer module to parts that use internals that use RPM props.

> [ERR 07:44:45.189] [RasterPropMonitor]: No RasterPropMonitorComputer module found on part rektmk1a for prop JSIStockPower in internal rektInternal

**Comment by korAPUcard** [comment] 2024-03-31 14:46
I apologize for providing insufficient information. My attachment files are here: [Google Drive](https://drive.google.com/drive/folders/1aXWXv3erRLU95NBqxUMzyXS14LfzXB_N?usp=sharing)

**Comment by linuxgurugamer** [comment] 2024-03-31 14:50
Fixed in new release

**Closed as completed by linuxgurugamer** 2024-03-31 14:50 UTC
